### ISSUE TITLE
Does this extension support workspaceFolder as a relative path for extensions?

### ISSUE THREAD

**Issue by Ryang20718** [oxdev03/pvmp#1]
some of my vscode settings use the variable `workspaceFolder` to define root. is this extension able to do the same?
```
  "go.alternateTools": {
    "go": "${workspaceFolder}/tools/go"
  }
```

**Comment by oxdev03** [comment]
Currently it does not support it, but I will add it.

**Comment by oxdev03** [comment]
@Ryang20718 is included in the latest version.

**Comment by Ryang20718** [comment]
I appreciate it so much thank you <3
