### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by DaniGalicia** [oxdev03/pvmp#3]
I am using your extension to  private extensions.

In my company, We publish extensions to our Nexus repository, so we had to develop another extension to be able to sync with a local folder.
It would be great if Private Marketplace provided a way to periodically retrieve from a remote source.

**Comment by oxdev03** [comment]
Hi @DaniGalicia,
currently this is not planned as vscode is planning to natively to support "private extensions". They already did a poll, so private extensions might be supported soon.
